using System.Text.RegularExpressions;
using Npgsql;

namespace Lighthouse.Sanctuary.Api.Services;

public class DatabaseBootstrapper(
    IConfiguration configuration,
    IWebHostEnvironment environment,
    ILogger<DatabaseBootstrapper> logger)
{
    public async Task InitializeAsync()
    {
        var connectionString = configuration.GetConnectionString("DefaultConnection")
            ?? throw new InvalidOperationException("Missing connection string: DefaultConnection");

        var appBuilder = new NpgsqlConnectionStringBuilder(connectionString);
        var databaseName = appBuilder.Database;

        if (string.IsNullOrWhiteSpace(databaseName))
        {
            throw new InvalidOperationException("Database name is missing from the connection string.");
        }

        var adminBuilder = new NpgsqlConnectionStringBuilder(connectionString)
        {
            Database = "postgres"
        };

        await EnsureDatabaseExistsAsync(adminBuilder.ConnectionString, databaseName);

        var schemaPath = ResolveSqlPath(configuration["DatabaseBootstrap:SchemaFile"] ?? "../schema_postgres_supabase.sql");
        var seedPath = ResolveSqlPath(configuration["DatabaseBootstrap:SeedFile"] ?? "../seed_sample_data.sql");

        await using var connection = new NpgsqlConnection(connectionString);
        await connection.OpenAsync();

        logger.LogInformation("Applying schema from {SchemaPath}", schemaPath);
        await ExecuteSqlScriptAsync(connection, SanitizeSchemaSql(await File.ReadAllTextAsync(schemaPath)));
        await EnsureAuthTableExistsAsync(connection);

        var seedMode = (configuration["DatabaseBootstrap:SeedMode"] ?? "IfEmpty").Trim();
        var hasExistingData = await HasExistingDataAsync(connection);

        if (ShouldRunSeed(seedMode, hasExistingData))
        {
            logger.LogInformation("Applying seed data from {SeedPath}", seedPath);
            await ExecuteSqlScriptAsync(connection, SanitizeSeedSql(await File.ReadAllTextAsync(seedPath)));
        }
        else
        {
            logger.LogInformation(
                "Skipping seed data. SeedMode={SeedMode}, HasExistingData={HasExistingData}",
                seedMode,
                hasExistingData);
        }
    }

    private async Task EnsureDatabaseExistsAsync(string adminConnectionString, string databaseName)
    {
        await using var adminConnection = new NpgsqlConnection(adminConnectionString);
        await adminConnection.OpenAsync();

        await using var existsCommand = new NpgsqlCommand(
            "select 1 from pg_database where datname = @databaseName",
            adminConnection);
        existsCommand.Parameters.AddWithValue("databaseName", databaseName);

        var exists = await existsCommand.ExecuteScalarAsync();
        if (exists is not null)
        {
            logger.LogInformation("Database {DatabaseName} already exists.", databaseName);
            return;
        }

        logger.LogInformation("Creating database {DatabaseName}", databaseName);
        await using var createCommand = new NpgsqlCommand($"create database \"{databaseName}\"", adminConnection);
        await createCommand.ExecuteNonQueryAsync();
    }

    private string ResolveSqlPath(string configuredPath)
    {
        return Path.GetFullPath(Path.Combine(environment.ContentRootPath, configuredPath));
    }

    private static bool ShouldRunSeed(string seedMode, bool hasExistingData)
    {
        return seedMode.ToLowerInvariant() switch
        {
            "always" => true,
            "never" => false,
            _ => !hasExistingData
        };
    }

    private static async Task<bool> HasExistingDataAsync(NpgsqlConnection connection)
    {
        const string sql = """
                           select exists(select 1 from residents limit 1)
                               or exists(select 1 from supporters limit 1)
                               or exists(select 1 from donations limit 1);
                           """;

        await using var command = new NpgsqlCommand(sql, connection);
        var result = await command.ExecuteScalarAsync();
        return result is true;
    }

    private static async Task EnsureAuthTableExistsAsync(NpgsqlConnection connection)
    {
        const string sql = """
                           create table if not exists app_users (
                               app_user_id integer generated by default as identity primary key,
                               username text not null unique,
                               display_name text not null,
                               email text,
                               supporter_id integer references supporters(supporter_id),
                               password_hash text not null,
                               role text not null check (role in ('Admin', 'Donor')),
                               is_active boolean not null default true,
                               created_at timestamp not null default now()
                           );

                           alter table app_users add column if not exists supporter_id integer references supporters(supporter_id);
                           create index if not exists idx_app_users_username on app_users (username);
                           """;

        await ExecuteSqlScriptAsync(connection, sql);
    }

    private static string SanitizeSchemaSql(string sql)
    {
        var lines = sql
            .Split('\n')
            .Where(line =>
            {
                var trimmed = line.Trim();
                return !trimmed.Equals("begin;", StringComparison.OrdinalIgnoreCase)
                       && !trimmed.Equals("commit;", StringComparison.OrdinalIgnoreCase)
                       && !trimmed.StartsWith("create database ", StringComparison.OrdinalIgnoreCase);
            });

        return string.Join('\n', lines);
    }

    private static string SanitizeSeedSql(string sql)
    {
        var lines = sql
            .Split('\n')
            .Where(line =>
            {
                var trimmed = line.Trim();
                return !trimmed.Equals("begin;", StringComparison.OrdinalIgnoreCase)
                       && !trimmed.Equals("commit;", StringComparison.OrdinalIgnoreCase);
            });

        return string.Join('\n', lines);
    }

    private static async Task ExecuteSqlScriptAsync(NpgsqlConnection connection, string sql)
    {
        var statements = Regex
            .Split(sql, @"(?<=;)\s*(?:\r?\n)+")
            .Select(statement => statement.Trim())
            .Where(statement => !string.IsNullOrWhiteSpace(statement));

        foreach (var statement in statements)
        {
            await using var command = new NpgsqlCommand(statement, connection);
            await command.ExecuteNonQueryAsync();
        }
    }
}
