-- Lighthouse Sanctuary schema for Supabase/PostgreSQL
-- Built from INTEX W26 Case data dictionary and validated against provided CSV files.

begin;

create database lh_sanctuary;

create table if not exists safehouses (
    safehouse_id integer generated by default as identity primary key,
    safehouse_code text not null unique,
    name text not null,
    region text not null check (region in ('Luzon', 'Visayas', 'Mindanao')),
    city text not null,
    province text not null,
    country text not null default 'Philippines',
    open_date date not null,
    status text not null check (status in ('Active', 'Inactive')),
    capacity_girls integer not null check (capacity_girls >= 0),
    capacity_staff integer not null check (capacity_staff >= 0),
    current_occupancy integer not null check (current_occupancy >= 0),
    notes text,
    constraint safehouses_occupancy_le_capacity check (current_occupancy <= capacity_girls)
);

create table if not exists partners (
    partner_id integer generated by default as identity primary key,
    partner_name text not null,
    partner_type text not null check (partner_type in ('Organization', 'Individual')),
    role_type text not null check (role_type in ('Education', 'Evaluation', 'SafehouseOps', 'FindSafehouse', 'Logistics', 'Transport', 'Maintenance')),
    contact_name text,
    email text,
    phone text,
    region text check (region in ('Luzon', 'Visayas', 'Mindanao')),
    status text not null check (status in ('Active', 'Inactive')),
    start_date date not null,
    end_date date,
    notes text,
    constraint partners_date_range check (end_date is null or end_date >= start_date)
);

create table if not exists supporters (
    supporter_id integer generated by default as identity primary key,
    supporter_type text not null check (supporter_type in ('MonetaryDonor', 'InKindDonor', 'Volunteer', 'SkillsContributor', 'SocialMediaAdvocate', 'PartnerOrganization')),
    display_name text not null,
    organization_name text,
    first_name text,
    last_name text,
    relationship_type text check (relationship_type in ('Local', 'International', 'PartnerOrganization')),
    region text check (region in ('Luzon', 'Visayas', 'Mindanao')),
    country text,
    email text,
    phone text,
    status text not null check (status in ('Active', 'Inactive')),
    created_at timestamp not null,
    first_donation_date date,
    acquisition_channel text check (acquisition_channel in ('Website', 'SocialMedia', 'Event', 'WordOfMouth', 'PartnerReferral', 'Church'))
);

create table if not exists residents (
    resident_id integer generated by default as identity primary key,
    case_control_no text not null unique,
    internal_code text not null unique,
    safehouse_id integer not null references safehouses(safehouse_id),
    case_status text not null check (case_status in ('Active', 'Closed', 'Transferred')),
    sex text not null check (sex in ('F')),
    date_of_birth date not null,
    birth_status text check (birth_status in ('Marital', 'Non-Marital')),
    place_of_birth text,
    religion text,
    case_category text check (case_category in ('Abandoned', 'Foundling', 'Surrendered', 'Neglected')),
    sub_cat_orphaned boolean not null default false,
    sub_cat_trafficked boolean not null default false,
    sub_cat_child_labor boolean not null default false,
    sub_cat_physical_abuse boolean not null default false,
    sub_cat_sexual_abuse boolean not null default false,
    sub_cat_osaec boolean not null default false,
    sub_cat_cicl boolean not null default false,
    sub_cat_at_risk boolean not null default false,
    sub_cat_street_child boolean not null default false,
    sub_cat_child_with_hiv boolean not null default false,
    is_pwd boolean not null default false,
    pwd_type text,
    has_special_needs boolean not null default false,
    special_needs_diagnosis text,
    family_is_4ps boolean not null default false,
    family_solo_parent boolean not null default false,
    family_indigenous boolean not null default false,
    family_parent_pwd boolean not null default false,
    family_informal_settler boolean not null default false,
    date_of_admission date not null,
    age_upon_admission text,
    present_age text,
    length_of_stay text,
    referral_source text check (referral_source in ('Government Agency', 'NGO', 'Police', 'Self-Referral', 'Community', 'Court Order')),
    referring_agency_person text,
    date_colb_registered date,
    date_colb_obtained date,
    assigned_social_worker text,
    initial_case_assessment text,
    date_case_study_prepared date,
    reintegration_type text check (reintegration_type in ('Family Reunification', 'Foster Care', 'Adoption (Domestic)', 'Adoption (Inter-Country)', 'Independent Living', 'None')),
    reintegration_status text check (reintegration_status in ('Not Started', 'In Progress', 'Completed', 'On Hold')),
    initial_risk_level text check (initial_risk_level in ('Low', 'Medium', 'High', 'Critical')),
    current_risk_level text check (current_risk_level in ('Low', 'Medium', 'High', 'Critical')),
    date_enrolled date,
    date_closed date,
    created_at timestamp not null,
    notes_restricted text,
    constraint residents_close_after_admit check (date_closed is null or date_closed >= date_of_admission)
);

create table if not exists social_media_posts (
    post_id integer generated by default as identity primary key,
    platform text not null check (platform in ('Facebook', 'Instagram', 'Twitter', 'TikTok', 'LinkedIn', 'YouTube', 'WhatsApp')),
    platform_post_id text not null unique,
    post_url text,
    created_at timestamp not null,
    day_of_week text check (day_of_week in ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')),
    post_hour integer check (post_hour between 0 and 23),
    post_type text check (post_type in ('ImpactStory', 'Campaign', 'EventPromotion', 'ThankYou', 'EducationalContent', 'FundraisingAppeal')),
    media_type text check (media_type in ('Photo', 'Video', 'Carousel', 'Text', 'Reel')),
    caption text,
    hashtags text,
    num_hashtags integer check (num_hashtags is null or num_hashtags >= 0),
    mentions_count integer check (mentions_count is null or mentions_count >= 0),
    has_call_to_action boolean not null default false,
    call_to_action_type text check (call_to_action_type in ('DonateNow', 'LearnMore', 'ShareStory', 'SignUp')),
    content_topic text check (content_topic in ('Education', 'Health', 'Reintegration', 'DonorImpact', 'SafehouseLife', 'EventRecap', 'CampaignLaunch', 'Gratitude', 'AwarenessRaising')),
    sentiment_tone text check (sentiment_tone in ('Hopeful', 'Urgent', 'Celebratory', 'Informative', 'Grateful', 'Emotional')),
    caption_length integer check (caption_length is null or caption_length >= 0),
    features_resident_story boolean not null default false,
    campaign_name text,
    is_boosted boolean not null default false,
    boost_budget_php numeric(12,2),
    impressions integer check (impressions is null or impressions >= 0),
    reach integer check (reach is null or reach >= 0),
    likes integer check (likes is null or likes >= 0),
    comments integer check (comments is null or comments >= 0),
    shares integer check (shares is null or shares >= 0),
    saves integer check (saves is null or saves >= 0),
    click_throughs integer check (click_throughs is null or click_throughs >= 0),
    video_views integer check (video_views is null or video_views >= 0),
    engagement_rate numeric(8,4),
    profile_visits integer check (profile_visits is null or profile_visits >= 0),
    donation_referrals integer check (donation_referrals is null or donation_referrals >= 0),
    estimated_donation_value_php numeric(14,2),
    follower_count_at_post integer check (follower_count_at_post is null or follower_count_at_post >= 0),
    watch_time_seconds integer check (watch_time_seconds is null or watch_time_seconds >= 0),
    avg_view_duration_seconds integer check (avg_view_duration_seconds is null or avg_view_duration_seconds >= 0),
    subscriber_count_at_post integer check (subscriber_count_at_post is null or subscriber_count_at_post >= 0),
    forwards integer check (forwards is null or forwards >= 0)
);

create table if not exists donations (
    donation_id integer generated by default as identity primary key,
    supporter_id integer not null references supporters(supporter_id),
    donation_type text not null check (donation_type in ('Monetary', 'InKind', 'Time', 'Skills', 'SocialMedia')),
    donation_date date not null,
    is_recurring boolean not null default false,
    campaign_name text,
    channel_source text check (channel_source in ('Campaign', 'Event', 'Direct', 'SocialMedia', 'PartnerReferral')),
    currency_code text,
    amount numeric(14,2),
    estimated_value numeric(14,2),
    impact_unit text check (impact_unit in ('pesos', 'items', 'hours', 'campaigns')),
    notes text,
    referral_post_id integer references social_media_posts(post_id),
    constraint donations_amount_nonnegative check (amount is null or amount >= 0),
    constraint donations_estimated_nonnegative check (estimated_value is null or estimated_value >= 0)
);

create table if not exists partner_assignments (
    assignment_id integer generated by default as identity primary key,
    partner_id integer not null references partners(partner_id),
    safehouse_id integer references safehouses(safehouse_id),
    program_area text not null check (program_area in ('Education', 'Wellbeing', 'Operations', 'Transport', 'Maintenance')),
    assignment_start date not null,
    assignment_end date,
    responsibility_notes text,
    is_primary boolean not null default false,
    status text not null check (status in ('Active', 'Ended')),
    constraint partner_assignments_date_range check (assignment_end is null or assignment_end >= assignment_start)
);

create table if not exists in_kind_donation_items (
    item_id integer generated by default as identity primary key,
    donation_id integer not null references donations(donation_id) on delete cascade,
    item_name text not null,
    item_category text check (item_category in ('Food', 'Supplies', 'Clothing', 'SchoolMaterials', 'Hygiene', 'Furniture', 'Medical')),
    quantity integer not null check (quantity > 0),
    unit_of_measure text check (unit_of_measure in ('pcs', 'boxes', 'kg', 'sets', 'packs')),
    estimated_unit_value numeric(12,2) check (estimated_unit_value is null or estimated_unit_value >= 0),
    intended_use text check (intended_use in ('Meals', 'Education', 'Shelter', 'Hygiene', 'Health')),
    received_condition text check (received_condition in ('New', 'Good', 'Fair'))
);

create table if not exists donation_allocations (
    allocation_id integer generated by default as identity primary key,
    donation_id integer not null references donations(donation_id) on delete cascade,
    safehouse_id integer not null references safehouses(safehouse_id),
    program_area text not null check (program_area in ('Education', 'Wellbeing', 'Operations', 'Transport', 'Maintenance', 'Outreach')),
    amount_allocated numeric(14,2) not null check (amount_allocated >= 0),
    allocation_date date not null,
    allocation_notes text
);

create table if not exists process_recordings (
    recording_id integer generated by default as identity primary key,
    resident_id integer not null references residents(resident_id) on delete cascade,
    session_date date not null,
    social_worker text,
    session_type text check (session_type in ('Individual', 'Group')),
    session_duration_minutes integer check (session_duration_minutes is null or session_duration_minutes > 0),
    emotional_state_observed text check (emotional_state_observed in ('Calm', 'Anxious', 'Sad', 'Angry', 'Hopeful', 'Withdrawn', 'Happy', 'Distressed')),
    emotional_state_end text check (emotional_state_end in ('Calm', 'Anxious', 'Sad', 'Angry', 'Hopeful', 'Withdrawn', 'Happy', 'Distressed')),
    session_narrative text,
    interventions_applied text,
    follow_up_actions text,
    progress_noted boolean not null default false,
    concerns_flagged boolean not null default false,
    referral_made boolean not null default false,
    notes_restricted text
);

create table if not exists home_visitations (
    visitation_id integer generated by default as identity primary key,
    resident_id integer not null references residents(resident_id) on delete cascade,
    visit_date date not null,
    social_worker text,
    visit_type text check (visit_type in ('Initial Assessment', 'Routine Follow-Up', 'Reintegration Assessment', 'Post-Placement Monitoring', 'Emergency')),
    location_visited text,
    family_members_present text,
    purpose text,
    observations text,
    family_cooperation_level text check (family_cooperation_level in ('Highly Cooperative', 'Cooperative', 'Neutral', 'Uncooperative')),
    safety_concerns_noted boolean not null default false,
    follow_up_needed boolean not null default false,
    follow_up_notes text,
    visit_outcome text check (visit_outcome in ('Favorable', 'Needs Improvement', 'Unfavorable', 'Inconclusive'))
);

create table if not exists education_records (
    education_record_id integer generated by default as identity primary key,
    resident_id integer not null references residents(resident_id) on delete cascade,
    record_date date not null,
    education_level text check (education_level in ('Primary', 'Secondary', 'Vocational', 'CollegePrep')),
    school_name text,
    enrollment_status text,
    attendance_rate numeric(6,3) check (attendance_rate is null or (attendance_rate >= 0 and attendance_rate <= 1)),
    progress_percent numeric(5,2) check (progress_percent is null or (progress_percent >= 0 and progress_percent <= 100)),
    completion_status text check (completion_status in ('NotStarted', 'InProgress', 'Completed')),
    notes text
);

create table if not exists health_wellbeing_records (
    health_record_id integer generated by default as identity primary key,
    resident_id integer not null references residents(resident_id) on delete cascade,
    record_date date not null,
    general_health_score numeric(4,2) check (general_health_score is null or (general_health_score >= 1 and general_health_score <= 5)),
    nutrition_score numeric(4,2) check (nutrition_score is null or (nutrition_score >= 1 and nutrition_score <= 5)),
    sleep_quality_score numeric(4,2) check (sleep_quality_score is null or (sleep_quality_score >= 1 and sleep_quality_score <= 5)),
    energy_level_score numeric(4,2) check (energy_level_score is null or (energy_level_score >= 1 and energy_level_score <= 5)),
    height_cm numeric(6,2) check (height_cm is null or height_cm > 0),
    weight_kg numeric(6,2) check (weight_kg is null or weight_kg > 0),
    bmi numeric(5,2) check (bmi is null or bmi > 0),
    medical_checkup_done boolean not null default false,
    dental_checkup_done boolean not null default false,
    psychological_checkup_done boolean not null default false,
    notes text
);

create table if not exists intervention_plans (
    plan_id integer generated by default as identity primary key,
    resident_id integer not null references residents(resident_id) on delete cascade,
    plan_category text check (plan_category in ('Safety', 'Psychosocial', 'Education', 'Physical Health', 'Legal', 'Reintegration')),
    plan_description text not null,
    services_provided text,
    target_value numeric(10,2),
    target_date date,
    status text check (status in ('Open', 'In Progress', 'Achieved', 'On Hold', 'Closed')),
    case_conference_date date,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table if not exists incident_reports (
    incident_id integer generated by default as identity primary key,
    resident_id integer not null references residents(resident_id) on delete cascade,
    safehouse_id integer not null references safehouses(safehouse_id),
    incident_date date not null,
    incident_type text check (incident_type in ('Behavioral', 'Medical', 'Security', 'RunawayAttempt', 'SelfHarm', 'ConflictWithPeer', 'PropertyDamage')),
    severity text check (severity in ('Low', 'Medium', 'High')),
    description text,
    response_taken text,
    resolved boolean not null default false,
    resolution_date date,
    reported_by text,
    follow_up_required boolean not null default false,
    constraint incident_resolution_check check (resolution_date is null or resolution_date >= incident_date)
);

create table if not exists safehouse_monthly_metrics (
    metric_id integer generated by default as identity primary key,
    safehouse_id integer not null references safehouses(safehouse_id),
    month_start date not null,
    month_end date not null,
    active_residents integer not null check (active_residents >= 0),
    avg_education_progress numeric(5,2) check (avg_education_progress is null or (avg_education_progress >= 0 and avg_education_progress <= 100)),
    avg_health_score numeric(4,2) check (avg_health_score is null or (avg_health_score >= 1 and avg_health_score <= 5)),
    process_recording_count integer not null check (process_recording_count >= 0),
    home_visitation_count integer not null check (home_visitation_count >= 0),
    incident_count integer not null check (incident_count >= 0),
    notes text,
    constraint safehouse_metrics_month_range check (month_end >= month_start),
    constraint safehouse_metrics_unique_month unique (safehouse_id, month_start)
);


create table if not exists public_impact_snapshots (
    snapshot_id integer generated by default as identity primary key,
    snapshot_date date not null unique,
    headline text not null,
    summary_text text,
    -- Kept as text because source CSV uses single-quoted JSON-like payload strings.
    metric_payload_json text,
    is_published boolean not null default false,
    published_at date
);

create index if not exists idx_residents_safehouse on residents (safehouse_id);
create index if not exists idx_donations_supporter_date on donations (supporter_id, donation_date);
create index if not exists idx_donations_referral_post on donations (referral_post_id);
create index if not exists idx_process_recordings_resident_date on process_recordings (resident_id, session_date);
create index if not exists idx_home_visitations_resident_date on home_visitations (resident_id, visit_date);
create index if not exists idx_education_records_resident_date on education_records (resident_id, record_date);
create index if not exists idx_health_records_resident_date on health_wellbeing_records (resident_id, record_date);
create index if not exists idx_incident_reports_resident_date on incident_reports (resident_id, incident_date);
create index if not exists idx_social_posts_created_at on social_media_posts (created_at);
create index if not exists idx_allocations_donation on donation_allocations (donation_id);

commit;
