-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.app_users
(
    app_user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    username text COLLATE pg_catalog."default" NOT NULL,
    display_name text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default",
    supporter_id integer,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    role text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT app_users_pkey PRIMARY KEY (app_user_id),
    CONSTRAINT app_users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.donation_allocations
(
    allocation_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    donation_id integer NOT NULL,
    safehouse_id integer NOT NULL,
    program_area text COLLATE pg_catalog."default" NOT NULL,
    amount_allocated numeric(14, 2) NOT NULL,
    allocation_date date NOT NULL,
    allocation_notes text COLLATE pg_catalog."default",
    CONSTRAINT donation_allocations_pkey PRIMARY KEY (allocation_id)
);

CREATE TABLE IF NOT EXISTS public.donations
(
    donation_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    supporter_id integer NOT NULL,
    donation_type text COLLATE pg_catalog."default" NOT NULL,
    donation_date date NOT NULL,
    is_recurring boolean NOT NULL DEFAULT false,
    campaign_name text COLLATE pg_catalog."default",
    channel_source text COLLATE pg_catalog."default",
    currency_code text COLLATE pg_catalog."default",
    amount numeric(14, 2),
    estimated_value numeric(14, 2),
    impact_unit text COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    referral_post_id integer,
    CONSTRAINT donations_pkey PRIMARY KEY (donation_id)
);

CREATE TABLE IF NOT EXISTS public.education_records
(
    education_record_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    resident_id integer NOT NULL,
    record_date date NOT NULL,
    education_level text COLLATE pg_catalog."default",
    school_name text COLLATE pg_catalog."default",
    enrollment_status text COLLATE pg_catalog."default",
    attendance_rate numeric(6, 3),
    progress_percent numeric(5, 2),
    completion_status text COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    CONSTRAINT education_records_pkey PRIMARY KEY (education_record_id)
);

CREATE TABLE IF NOT EXISTS public.health_wellbeing_records
(
    health_record_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    resident_id integer NOT NULL,
    record_date date NOT NULL,
    general_health_score numeric(4, 2),
    nutrition_score numeric(4, 2),
    sleep_quality_score numeric(4, 2),
    energy_level_score numeric(4, 2),
    height_cm numeric(6, 2),
    weight_kg numeric(6, 2),
    bmi numeric(5, 2),
    medical_checkup_done boolean NOT NULL DEFAULT false,
    dental_checkup_done boolean NOT NULL DEFAULT false,
    psychological_checkup_done boolean NOT NULL DEFAULT false,
    notes text COLLATE pg_catalog."default",
    CONSTRAINT health_wellbeing_records_pkey PRIMARY KEY (health_record_id)
);

CREATE TABLE IF NOT EXISTS public.home_visitations
(
    visitation_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    resident_id integer NOT NULL,
    visit_date date NOT NULL,
    social_worker text COLLATE pg_catalog."default",
    visit_type text COLLATE pg_catalog."default",
    location_visited text COLLATE pg_catalog."default",
    family_members_present text COLLATE pg_catalog."default",
    purpose text COLLATE pg_catalog."default",
    observations text COLLATE pg_catalog."default",
    family_cooperation_level text COLLATE pg_catalog."default",
    safety_concerns_noted boolean NOT NULL DEFAULT false,
    follow_up_needed boolean NOT NULL DEFAULT false,
    follow_up_notes text COLLATE pg_catalog."default",
    visit_outcome text COLLATE pg_catalog."default",
    CONSTRAINT home_visitations_pkey PRIMARY KEY (visitation_id)
);

CREATE TABLE IF NOT EXISTS public.in_kind_donation_items
(
    item_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    donation_id integer NOT NULL,
    item_name text COLLATE pg_catalog."default" NOT NULL,
    item_category text COLLATE pg_catalog."default",
    quantity integer NOT NULL,
    unit_of_measure text COLLATE pg_catalog."default",
    estimated_unit_value numeric(12, 2),
    intended_use text COLLATE pg_catalog."default",
    received_condition text COLLATE pg_catalog."default",
    CONSTRAINT in_kind_donation_items_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public.incident_reports
(
    incident_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    resident_id integer NOT NULL,
    safehouse_id integer NOT NULL,
    incident_date date NOT NULL,
    incident_type text COLLATE pg_catalog."default",
    severity text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    response_taken text COLLATE pg_catalog."default",
    resolved boolean NOT NULL DEFAULT false,
    resolution_date date,
    reported_by text COLLATE pg_catalog."default",
    follow_up_required boolean NOT NULL DEFAULT false,
    CONSTRAINT incident_reports_pkey PRIMARY KEY (incident_id)
);

CREATE TABLE IF NOT EXISTS public.intervention_plans
(
    plan_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    resident_id integer NOT NULL,
    plan_category text COLLATE pg_catalog."default",
    plan_description text COLLATE pg_catalog."default" NOT NULL,
    services_provided text COLLATE pg_catalog."default",
    target_value numeric(10, 2),
    target_date date,
    status text COLLATE pg_catalog."default",
    case_conference_date date,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    CONSTRAINT intervention_plans_pkey PRIMARY KEY (plan_id)
);

CREATE TABLE IF NOT EXISTS public.ml_donor_churn_scores
(
    supporter_id integer NOT NULL,
    churn_score numeric(5, 4) NOT NULL,
    churn_tier text COLLATE pg_catalog."default" NOT NULL DEFAULT 'Medium'::text,
    model_version text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pipeline1-v1'::text,
    scored_at_utc timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ml_donor_churn_scores_pkey PRIMARY KEY (supporter_id)
);

CREATE TABLE IF NOT EXISTS public.ml_donor_impact_predictions
(
    supporter_id integer NOT NULL,
    impact_score numeric(5, 4) NOT NULL,
    predicted_top_program_area text COLLATE pg_catalog."default" NOT NULL DEFAULT 'Education'::text,
    predicted_education_share numeric(5, 4) NOT NULL,
    model_version text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pipeline5-v1'::text,
    scored_at_utc timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ml_donor_impact_predictions_pkey PRIMARY KEY (supporter_id)
);

CREATE TABLE IF NOT EXISTS public.ml_donor_uplift_scores
(
    supporter_id integer NOT NULL,
    uplift_score numeric(5, 4) NOT NULL,
    model_version text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pipeline4-v1'::text,
    scored_at_utc timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ml_donor_uplift_scores_pkey PRIMARY KEY (supporter_id)
);

CREATE TABLE IF NOT EXISTS public.ml_resident_readiness_scores
(
    resident_id integer NOT NULL,
    readiness_score numeric(5, 4) NOT NULL,
    readiness_tier text COLLATE pg_catalog."default" NOT NULL DEFAULT 'Developing'::text,
    model_version text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pipeline3-v1'::text,
    scored_at_utc timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ml_resident_readiness_scores_pkey PRIMARY KEY (resident_id)
);

CREATE TABLE IF NOT EXISTS public.ml_social_post_scores
(
    post_id integer NOT NULL,
    churn_score numeric(5, 4) NOT NULL,
    uplift_score numeric(5, 4) NOT NULL,
    model_version text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pipeline2-4-v1'::text,
    scored_at_utc timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ml_social_post_scores_pkey PRIMARY KEY (post_id)
);

CREATE TABLE IF NOT EXISTS public.partner_assignments
(
    assignment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    partner_id integer NOT NULL,
    safehouse_id integer,
    program_area text COLLATE pg_catalog."default" NOT NULL,
    assignment_start date NOT NULL,
    assignment_end date,
    responsibility_notes text COLLATE pg_catalog."default",
    is_primary boolean NOT NULL DEFAULT false,
    status text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT partner_assignments_pkey PRIMARY KEY (assignment_id)
);

CREATE TABLE IF NOT EXISTS public.partners
(
    partner_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    partner_name text COLLATE pg_catalog."default" NOT NULL,
    partner_type text COLLATE pg_catalog."default" NOT NULL,
    role_type text COLLATE pg_catalog."default" NOT NULL,
    contact_name text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    phone text COLLATE pg_catalog."default",
    region text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL,
    end_date date,
    notes text COLLATE pg_catalog."default",
    CONSTRAINT partners_pkey PRIMARY KEY (partner_id)
);

CREATE TABLE IF NOT EXISTS public.process_recordings
(
    recording_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    resident_id integer NOT NULL,
    session_date date NOT NULL,
    social_worker text COLLATE pg_catalog."default",
    session_type text COLLATE pg_catalog."default",
    session_duration_minutes integer,
    emotional_state_observed text COLLATE pg_catalog."default",
    emotional_state_end text COLLATE pg_catalog."default",
    session_narrative text COLLATE pg_catalog."default",
    interventions_applied text COLLATE pg_catalog."default",
    follow_up_actions text COLLATE pg_catalog."default",
    progress_noted boolean NOT NULL DEFAULT false,
    concerns_flagged boolean NOT NULL DEFAULT false,
    referral_made boolean NOT NULL DEFAULT false,
    notes_restricted text COLLATE pg_catalog."default",
    CONSTRAINT process_recordings_pkey PRIMARY KEY (recording_id)
);

CREATE TABLE IF NOT EXISTS public.public_impact_snapshots
(
    snapshot_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    snapshot_date date NOT NULL,
    headline text COLLATE pg_catalog."default" NOT NULL,
    summary_text text COLLATE pg_catalog."default",
    metric_payload_json text COLLATE pg_catalog."default",
    is_published boolean NOT NULL DEFAULT false,
    published_at date,
    CONSTRAINT public_impact_snapshots_pkey PRIMARY KEY (snapshot_id),
    CONSTRAINT public_impact_snapshots_snapshot_date_key UNIQUE (snapshot_date)
);

CREATE TABLE IF NOT EXISTS public.residents
(
    resident_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    case_control_no text COLLATE pg_catalog."default" NOT NULL,
    internal_code text COLLATE pg_catalog."default" NOT NULL,
    safehouse_id integer NOT NULL,
    case_status text COLLATE pg_catalog."default" NOT NULL,
    sex text COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date NOT NULL,
    birth_status text COLLATE pg_catalog."default",
    place_of_birth text COLLATE pg_catalog."default",
    religion text COLLATE pg_catalog."default",
    case_category text COLLATE pg_catalog."default",
    sub_cat_orphaned boolean NOT NULL DEFAULT false,
    sub_cat_trafficked boolean NOT NULL DEFAULT false,
    sub_cat_child_labor boolean NOT NULL DEFAULT false,
    sub_cat_physical_abuse boolean NOT NULL DEFAULT false,
    sub_cat_sexual_abuse boolean NOT NULL DEFAULT false,
    sub_cat_osaec boolean NOT NULL DEFAULT false,
    sub_cat_cicl boolean NOT NULL DEFAULT false,
    sub_cat_at_risk boolean NOT NULL DEFAULT false,
    sub_cat_street_child boolean NOT NULL DEFAULT false,
    sub_cat_child_with_hiv boolean NOT NULL DEFAULT false,
    is_pwd boolean NOT NULL DEFAULT false,
    pwd_type text COLLATE pg_catalog."default",
    has_special_needs boolean NOT NULL DEFAULT false,
    special_needs_diagnosis text COLLATE pg_catalog."default",
    family_is_4ps boolean NOT NULL DEFAULT false,
    family_solo_parent boolean NOT NULL DEFAULT false,
    family_indigenous boolean NOT NULL DEFAULT false,
    family_parent_pwd boolean NOT NULL DEFAULT false,
    family_informal_settler boolean NOT NULL DEFAULT false,
    date_of_admission date NOT NULL,
    age_upon_admission text COLLATE pg_catalog."default",
    present_age text COLLATE pg_catalog."default",
    length_of_stay text COLLATE pg_catalog."default",
    referral_source text COLLATE pg_catalog."default",
    referring_agency_person text COLLATE pg_catalog."default",
    date_colb_registered date,
    date_colb_obtained date,
    assigned_social_worker text COLLATE pg_catalog."default",
    initial_case_assessment text COLLATE pg_catalog."default",
    date_case_study_prepared date,
    reintegration_type text COLLATE pg_catalog."default",
    reintegration_status text COLLATE pg_catalog."default",
    initial_risk_level text COLLATE pg_catalog."default",
    current_risk_level text COLLATE pg_catalog."default",
    date_enrolled date,
    date_closed date,
    created_at timestamp without time zone NOT NULL,
    notes_restricted text COLLATE pg_catalog."default",
    CONSTRAINT residents_pkey PRIMARY KEY (resident_id),
    CONSTRAINT residents_case_control_no_key UNIQUE (case_control_no),
    CONSTRAINT residents_internal_code_key UNIQUE (internal_code)
);

CREATE TABLE IF NOT EXISTS public.safehouse_monthly_metrics
(
    metric_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    safehouse_id integer NOT NULL,
    month_start date NOT NULL,
    month_end date NOT NULL,
    active_residents integer NOT NULL,
    avg_education_progress numeric(5, 2),
    avg_health_score numeric(4, 2),
    process_recording_count integer NOT NULL,
    home_visitation_count integer NOT NULL,
    incident_count integer NOT NULL,
    notes text COLLATE pg_catalog."default",
    CONSTRAINT safehouse_monthly_metrics_pkey PRIMARY KEY (metric_id),
    CONSTRAINT safehouse_metrics_unique_month UNIQUE (safehouse_id, month_start)
);

CREATE TABLE IF NOT EXISTS public.safehouses
(
    safehouse_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    safehouse_code text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    region text COLLATE pg_catalog."default" NOT NULL,
    city text COLLATE pg_catalog."default" NOT NULL,
    province text COLLATE pg_catalog."default" NOT NULL,
    country text COLLATE pg_catalog."default" NOT NULL DEFAULT 'Philippines'::text,
    open_date date NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL,
    capacity_girls integer NOT NULL,
    capacity_staff integer NOT NULL,
    current_occupancy integer NOT NULL,
    notes text COLLATE pg_catalog."default",
    CONSTRAINT safehouses_pkey PRIMARY KEY (safehouse_id),
    CONSTRAINT safehouses_safehouse_code_key UNIQUE (safehouse_code)
);

CREATE TABLE IF NOT EXISTS public.social_media_posts
(
    post_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    platform text COLLATE pg_catalog."default" NOT NULL,
    platform_post_id text COLLATE pg_catalog."default" NOT NULL,
    post_url text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL,
    day_of_week text COLLATE pg_catalog."default",
    post_hour integer,
    post_type text COLLATE pg_catalog."default",
    media_type text COLLATE pg_catalog."default",
    caption text COLLATE pg_catalog."default",
    hashtags text COLLATE pg_catalog."default",
    num_hashtags integer,
    mentions_count integer,
    has_call_to_action boolean NOT NULL DEFAULT false,
    call_to_action_type text COLLATE pg_catalog."default",
    content_topic text COLLATE pg_catalog."default",
    sentiment_tone text COLLATE pg_catalog."default",
    caption_length integer,
    features_resident_story boolean NOT NULL DEFAULT false,
    campaign_name text COLLATE pg_catalog."default",
    is_boosted boolean NOT NULL DEFAULT false,
    boost_budget_php numeric(12, 2),
    impressions integer,
    reach integer,
    likes integer,
    comments integer,
    shares integer,
    saves integer,
    click_throughs integer,
    video_views integer,
    engagement_rate numeric(8, 4),
    profile_visits integer,
    donation_referrals integer,
    estimated_donation_value_php numeric(14, 2),
    follower_count_at_post integer,
    watch_time_seconds integer,
    avg_view_duration_seconds integer,
    subscriber_count_at_post integer,
    forwards integer,
    CONSTRAINT social_media_posts_pkey PRIMARY KEY (post_id),
    CONSTRAINT social_media_posts_platform_post_id_key UNIQUE (platform_post_id)
);

CREATE TABLE IF NOT EXISTS public.supporters
(
    supporter_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    supporter_type text COLLATE pg_catalog."default" NOT NULL,
    display_name text COLLATE pg_catalog."default" NOT NULL,
    organization_name text COLLATE pg_catalog."default",
    first_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    relationship_type text COLLATE pg_catalog."default",
    region text COLLATE pg_catalog."default",
    country text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    phone text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL,
    first_donation_date date,
    acquisition_channel text COLLATE pg_catalog."default",
    CONSTRAINT supporters_pkey PRIMARY KEY (supporter_id)
);

ALTER TABLE IF EXISTS public.app_users
    ADD CONSTRAINT app_users_supporter_id_fkey FOREIGN KEY (supporter_id)
    REFERENCES public.supporters (supporter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.donation_allocations
    ADD CONSTRAINT donation_allocations_donation_id_fkey FOREIGN KEY (donation_id)
    REFERENCES public.donations (donation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_allocations_donation
    ON public.donation_allocations(donation_id);


ALTER TABLE IF EXISTS public.donation_allocations
    ADD CONSTRAINT donation_allocations_safehouse_id_fkey FOREIGN KEY (safehouse_id)
    REFERENCES public.safehouses (safehouse_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.donations
    ADD CONSTRAINT donations_referral_post_id_fkey FOREIGN KEY (referral_post_id)
    REFERENCES public.social_media_posts (post_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_donations_referral_post
    ON public.donations(referral_post_id);


ALTER TABLE IF EXISTS public.donations
    ADD CONSTRAINT donations_supporter_id_fkey FOREIGN KEY (supporter_id)
    REFERENCES public.supporters (supporter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.education_records
    ADD CONSTRAINT education_records_resident_id_fkey FOREIGN KEY (resident_id)
    REFERENCES public.residents (resident_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.health_wellbeing_records
    ADD CONSTRAINT health_wellbeing_records_resident_id_fkey FOREIGN KEY (resident_id)
    REFERENCES public.residents (resident_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.home_visitations
    ADD CONSTRAINT home_visitations_resident_id_fkey FOREIGN KEY (resident_id)
    REFERENCES public.residents (resident_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.in_kind_donation_items
    ADD CONSTRAINT in_kind_donation_items_donation_id_fkey FOREIGN KEY (donation_id)
    REFERENCES public.donations (donation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.incident_reports
    ADD CONSTRAINT incident_reports_resident_id_fkey FOREIGN KEY (resident_id)
    REFERENCES public.residents (resident_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.incident_reports
    ADD CONSTRAINT incident_reports_safehouse_id_fkey FOREIGN KEY (safehouse_id)
    REFERENCES public.safehouses (safehouse_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.intervention_plans
    ADD CONSTRAINT intervention_plans_resident_id_fkey FOREIGN KEY (resident_id)
    REFERENCES public.residents (resident_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ml_donor_churn_scores
    ADD CONSTRAINT ml_donor_churn_scores_supporter_id_fkey FOREIGN KEY (supporter_id)
    REFERENCES public.supporters (supporter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ml_donor_churn_scores_pkey
    ON public.ml_donor_churn_scores(supporter_id);


ALTER TABLE IF EXISTS public.ml_donor_impact_predictions
    ADD CONSTRAINT ml_donor_impact_predictions_supporter_id_fkey FOREIGN KEY (supporter_id)
    REFERENCES public.supporters (supporter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ml_donor_impact_predictions_pkey
    ON public.ml_donor_impact_predictions(supporter_id);


ALTER TABLE IF EXISTS public.ml_donor_uplift_scores
    ADD CONSTRAINT ml_donor_uplift_scores_supporter_id_fkey FOREIGN KEY (supporter_id)
    REFERENCES public.supporters (supporter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ml_donor_uplift_scores_pkey
    ON public.ml_donor_uplift_scores(supporter_id);


ALTER TABLE IF EXISTS public.ml_resident_readiness_scores
    ADD CONSTRAINT ml_resident_readiness_scores_resident_id_fkey FOREIGN KEY (resident_id)
    REFERENCES public.residents (resident_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ml_resident_readiness_scores_pkey
    ON public.ml_resident_readiness_scores(resident_id);


ALTER TABLE IF EXISTS public.ml_social_post_scores
    ADD CONSTRAINT ml_social_post_scores_post_id_fkey FOREIGN KEY (post_id)
    REFERENCES public.social_media_posts (post_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ml_social_post_scores_pkey
    ON public.ml_social_post_scores(post_id);


ALTER TABLE IF EXISTS public.partner_assignments
    ADD CONSTRAINT partner_assignments_partner_id_fkey FOREIGN KEY (partner_id)
    REFERENCES public.partners (partner_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.partner_assignments
    ADD CONSTRAINT partner_assignments_safehouse_id_fkey FOREIGN KEY (safehouse_id)
    REFERENCES public.safehouses (safehouse_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.process_recordings
    ADD CONSTRAINT process_recordings_resident_id_fkey FOREIGN KEY (resident_id)
    REFERENCES public.residents (resident_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.residents
    ADD CONSTRAINT residents_safehouse_id_fkey FOREIGN KEY (safehouse_id)
    REFERENCES public.safehouses (safehouse_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_residents_safehouse
    ON public.residents(safehouse_id);


ALTER TABLE IF EXISTS public.safehouse_monthly_metrics
    ADD CONSTRAINT safehouse_monthly_metrics_safehouse_id_fkey FOREIGN KEY (safehouse_id)
    REFERENCES public.safehouses (safehouse_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;