# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - lh-sanctuary-api

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore
        run: dotnet restore .\Lighthouse.Sanctuary.Api.csproj

      - name: Build with dotnet
        run: dotnet build .\Lighthouse.Sanctuary.Api.csproj --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish .\Lighthouse.Sanctuary.Api.csproj -c Release -o "${{ github.workspace }}/backend-publish" --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/backend-publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./backend-publish
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_31C7C051C20C4A1381276707C5D05E0B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5D38AD2B52E343CCA28A5F40683BEEDE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4A73066E6DDE4481A0EBF87461F15D0B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lh-sanctuary-api'
          slot-name: 'Production'
          package: ./backend-publish
